# Setup
title:        Lifting from the deep
tagline:      Description of the Lifting from the Deep paper.
baseurl:      "/Lifting-from-the-Deep-release"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Denis Tome
  url:        "https://denistome.github.io" 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown