# Setup
title:        "Lifting from the Deep: Convolutional 3D Pose Estimation from a Single Image"
tagline:      Denis Tome - Chris Russell - Lourdes Agapito
conference:   "Conference on Computer Vision and Pattern Recognition (CVPR) 2017"
baseurl:      "/Lifting-from-the-Deep-release"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Denis Tome
  url:        "https://denistome.github.io" 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown